version: "3.9"

services:
  contactapp-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ContactAppDb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  contactapp-api:
    build: .
    depends_on:
      contactapp-db:
        condition: service_healthy
    environment:
      # Burada connection string'i DB servis adıyla ayarlıyoruz
      ConnectionStrings__DefaultConnection: "Host=contactapp-db;Port=5432;Database=ContactAppDb;Username=postgres;Password=1234"
    ports:
      - "5001:5000"

volumes:
  db-data:
